docs/data.sql
src/main/resources/database.properties
src/main/webapp/WEB-INF/spring/applicationContext.xml
src/main/webapp/WEB-INF/spring/database-context/databaseContext.xml
src/test/java/com/everypet/member/data/dao/memberDaoTest.java

Database setting

---

README.md
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/index.tsx
frontend/src/layout/Header/Header.module.css
frontend/src/layout/Header/Header.tsx
frontend/src/layout/Header/realtimekeyword/Realtimekeyword.tsx
frontend/src/layout/Header/searchinput/Searchinput.module.css
frontend/src/layout/Header/searchinput/Searchinput.tsx
frontend/src/layout/category/Productcategory.tsx
frontend/src/pages/auth/Findauth.tsx
frontend/src/pages/auth/Login.tsx
frontend/src/pages/auth/Signup.tsx
frontend/src/pages/category/Pages1.tsx
frontend/src/pages/category/Pages2.tsx
frontend/src/pages/category/Pages3.tsx
frontend/src/pages/home/Home.tsx

react-router-dom돔 추가 후 index에서 라우터로 페이지를 구분함. 추가적으로 구분 해야 할 페이지들이 있지만 우선 메인 페이지부터 작업 예정

라우터로 페이지 구분

---

README.md
pom.xml
src/main/java/com/everypet/common/config/SwaggerConfig.java
src/main/webapp/WEB-INF/spring/appServlet/dispatcher-servlet.xml
src/main/webapp/WEB-INF/spring/spring-security/springSecurityContext.xml

Swagger 적용

---

README.md
src/main/java/com/everypet/common/config/DatabaseConfig.java
src/main/java/com/everypet/common/config/SecurityConfig.java
src/main/webapp/WEB-INF/spring/applicationContext.xml
src/main/webapp/index.jsp
src/test/java/com/everypet/member/data/dao/memberDaoTest.java

applicationContext.xml, dispatcher-servlet.xml, web.xml 제외
나머지 xml -> java로 리팩토링 작업 하였습니다.

xml -> java 코드로 리팩토링

---

frontend/src/pages/auth/Postcode.tsx
frontend/src/pages/auth/Signup.module.css
frontend/src/pages/auth/Signup.tsx

회원가입 html 작성 및 css 작성 아이디 비번 미 입력시 기초 코드만 작성 해 놓음, 추후 서버랑 연결 후 코드 작업 예정 기본적인 기능만 테스트함

회원가입 html 작성 및 다음 지도 api 연결 css작성

---

frontend/src/typings/AuthAPI.ts

axios interceptors 401에러 초기 코드 작성

:sparkles: axios interceptors 401에러 초기 코드 작성

---

frontend/src/components/common/Item.module.css
frontend/src/components/common/Item.tsx
frontend/src/components/common/ItemList.tsx
frontend/src/components/home/banner/Maincarousel.module.css
frontend/src/components/home/banner/Maincarousel.tsx
frontend/src/components/home/banner/slick.css

홈화면 브랜드 광고 UI 완성

---

src/main/java/com/everypet/product/controller/ProductController.java
src/main/java/com/everypet/product/data/dto/SelectProductDTO.java
src/main/java/com/everypet/product/service/impl/ProductServiceImpl.java

상품 정보 출력 PostMapping -> GetMapping 으로 변경했습니다!

:recycle: 상품 정보 출력 PostMapping -> GetMapping 으로 변경

---

src/main/java/com/everypet/global/util/mail/controller/EmailController.java

<p>
-- EmailController의 sendJoinMail 메서드에서 email 파라미터를 @RequestParam에서 @RequestBody로 변경

Refactor: Change @RequestParam to @RequestBody for email parameter in sendJoinMail

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/auth/Login.tsx
frontend/src/pages/auth/Signup.tsx
frontend/src/typings/AuthAPI.ts
frontend/src/typings/signup.ts

이메일 인증 및 토큰 AES암호화 

---

frontend/src/pages/moreInformation/MoreInformation.tsx
frontend/src/pages/moreInformation/moreInformation.module.css

물품 상세정보 css 추가 및 할인 가격 계산 기능 추가

feat: Add 물품 상세정보 css 추가 및 할인 가격 계산 기능 추가

---

src/main/java/com/everypet/global/util/mail/controller/EmailController.java
src/main/java/com/everypet/global/util/mail/service/EmailService.java
src/main/java/com/everypet/global/util/mail/service/impl/EmailServiceImpl.java

-- joinSendMail, sendMail 메소드의 매개값 String type 을 제거

Refactor: Update EmailService 사용하지 않는 String type 매개값 제거

---

src/main/java/com/everypet/cart/controller/CartApiController.java
src/main/java/com/everypet/cart/data/dao/CartMapper.java
src/main/java/com/everypet/cart/service/impl/CartServiceImpl.java
src/main/java/com/everypet/member/data/vo/Address.java
src/main/resources/mybatis/mybatis-mapper/cartMapper.xml

feat: ADD cart delete api

---

frontend/src/components/common/Item.tsx
frontend/src/components/home/Footer.module.css
frontend/src/components/timedeal/TimeItem.module.css
frontend/src/components/timedeal/TimeItem.tsx
frontend/src/index.tsx
frontend/src/layout/Header/TopMenu.module.css
frontend/src/layout/Header/TopMenu.tsx
frontend/src/layout/Header/Usermenu.tsx
frontend/src/pages/home/Root.tsx
frontend/src/pages/userService/CustomerService.module.css
frontend/src/pages/userService/CustomerService.tsx
frontend/src/pages/userService/MyPage.module.css
frontend/src/pages/userService/MyPage.tsx

feat: 마이페이지 기본 UI 작성

---

frontend/public/mock/real_rank.json
frontend/src/layout/Header/Modal.module.css
frontend/src/layout/Header/Modal.tsx
frontend/src/typings/layout.ts
package-lock.json

feat: 실시간 검색어 UI 수정

---

frontend/src/pages/moreInformation/MoreInformation.tsx
frontend/src/pages/moreInformation/moreInformation.module.css
frontend/src/typings/fetchProductDetails.ts

pages => moreInformation => SaleInformation(파일 삭제 해주세요)

feat: Add 상세페이지 상세설명 코드 일부 수정

---

frontend/src/pages/userService/Cart.tsx
frontend/src/pages/userService/Payment.module.css
frontend/src/pages/userService/Payment.tsx

feat: 주문결제 페이지 UI 작성

---

frontend/src/pages/auth/Signup.tsx
frontend/src/typings/AuthAPI.ts

feat: email 서버 통신 코드 수정

---

.github/workflows/cicd.yml
src/main/java/com/everypet/global/util/mail/controller/EmailController.java

feat: GitHub Actions CI/CD 파이프라인 추가

---

.github/workflows/cicd.yml

fix: ci/cd 버그 수정

---

.github/workflows/cicd.yml
src/main/java/com/everypet/global/config/DatabaseConfig.java

- Maven 설치 및 빌드 단계 추가
- application.properties 및 database.properties 파일 생성 및 설정 추가
- Google Cloud JSON 파일 생성 및 이동
- AWS Elastic Beanstalk 배포 단계 설정
- CI/CD 파이프라인에서 현재 시간 포맷팅 및 아티팩트 설정 추가

ci: GitHub Actions 워크플로우 추가 및 설정

---

.github/workflows/cicd.yml
src/main/java/com/everypet/global/config/DatabaseConfig.java
src/main/java/com/everypet/global/util/mail/controller/EmailController.java

everypet 1.0.0

---

.github/workflows/cicd.yml

- Maven 설치 및 빌드 단계 추가
- application.properties 및 database.properties 파일 생성 및 설정 추가
- Google Cloud JSON 파일 생성 및 이동
- AWS Elastic Beanstalk 배포 단계 설정
- CI/CD 파이프라인에서 현재 시간 포맷팅 및 아티팩트 설정 추가

feat: ci/cd 파이프라인 구축

---

README.md
pom.xml
src/main/java/com/everypet/cart/model/dto/CartItemDTO.java
src/main/java/com/everypet/global/config/MvcConfig.java
src/main/java/com/everypet/global/config/SwaggerConfig.java

1. 카트 아이디가 조회되지 않는 버그 수정
2. 스웨거 버전업 (3.0.0)

카트 아이디 표시 버그 수정 & 스웨거 버전업

---

.github/workflows/cicd.yml
frontend/src/pages/userService/Cart.tsx
frontend/src/pages/userService/Payment.tsx
frontend/src/utils/product/cart.ts
src/main/java/com/everypet/global/util/mail/controller/EmailController.java

cart의 타입명 수정 및 상품 삭제 버그 수정

---

Dockerfile
docker-compose.yml

chore: Dockerfile 및 docker-compose.yml 빌드 속도 개선

---

src/main/resources/mybatis/mybatis-context.xml

- 누락된 MyOrderListDTO 타입 별칭 추가로 오류 수정
미안합니다.

fix: mybatis-context 누락된 typeAlias 추가

---

frontend/src/components/common/SearchItemList.tsx
frontend/src/components/home/banner/slick-theme.css
frontend/src/layout/category/CategoryModal.tsx
frontend/src/layout/category/Categorymodal.module.css
frontend/src/layout/mobile/MobileSearchModal.tsx

feat: 메가 카테고리와 상세 카테고리 css 수정및 active css 를 추가해 가독성 향상

---

docs/data.sql
src/main/java/com/everypet/order/controller/OrderController.java
src/main/java/com/everypet/order/model/dao/OrderDetailMapper.java
src/main/java/com/everypet/order/model/dto/OrderDTO.java
src/main/java/com/everypet/order/service/OrderService.java
src/main/java/com/everypet/order/service/impl/OrderServiceImpl.java
src/main/java/com/everypet/product/controller/ProductController.java
src/main/java/com/everypet/product/model/dao/ProductMapper.java
src/main/java/com/everypet/product/service/ProductService.java
src/main/java/com/everypet/product/service/impl/ProductServiceImpl.java
src/main/resources/mybatis/mybatis-mapper/orderDetailMapper.xml
src/main/resources/mybatis/mybatis-mapper/orderMapper.xml
src/main/resources/mybatis/mybatis-mapper/productMapper.xml

1. 브랜드 별 상품 리스트 출력 기능 - 해당 브랜드 상품만 불러올때 사용
2. 운송장 번호 추가 기능 - 주문이후 배송이 시작하면 운송장 추가할때 사용

상품, 주문 기능 추가

---

docs/data.sql
src/main/java/com/everypet/order/controller/OrderController.java
src/main/java/com/everypet/order/model/dao/OrderDetailMapper.java
src/main/java/com/everypet/order/model/dto/OrderDTO.java
src/main/java/com/everypet/order/service/OrderService.java
src/main/java/com/everypet/order/service/impl/OrderServiceImpl.java
src/main/resources/mybatis/mybatis-mapper/orderDetailMapper.xml

feat : 주문 상세 보기 기능 추가

---

frontend/src/pages/moreInformation/MoreInformation.tsx
frontend/src/pages/moreInformation/ProductInquiry.tsx
frontend/src/pages/moreInformation/productInqulry.module.css
frontend/src/pages/moreInformation/review.tsx

feat: 리뷰 페이지 리뷰 쓰기 마크업 및 별점 기능 추가

---

src/main/java/com/everypet/payment/controller/PaymentController.java
src/main/java/com/everypet/payment/service/impl/paymentServiceImpl.java
src/main/java/com/everypet/product/controller/ProductController.java
src/main/java/com/everypet/product/model/dto/ProductDTO.java
src/main/java/com/everypet/product/service/ProductService.java
src/main/java/com/everypet/product/service/impl/ProductServiceImpl.java
src/main/resources/mybatis/mybatis-mapper/productMapper.xml

1. 결제 에러 catch 추가
2. 상품 추가 오류 해결

상품 결제 오류해결

---

src/main/java/com/everypet/auth/jwt/JWTManager.java
src/main/java/com/everypet/clound/service/CloudBucketService.java
src/main/java/com/everypet/clound/service/impl/GoogleBucketCloudService.java
src/main/java/com/everypet/global/config/RedisConfig.java
src/main/java/com/everypet/product/service/impl/ProductServiceImpl.java
src/main/java/com/everypet/review/service/impl/ReviewServiceImpl.java
src/main/java/com/everypet/support/controller/SellerInquiryReplyController.java
src/main/java/com/everypet/support/model/dao/SellerInquiryReplyMapper.java
src/main/java/com/everypet/support/service/SellerInquiryReplyService.java
src/main/java/com/everypet/support/service/impl/SellerInquiryReplyServiceImpl.java

- getRoles 메서드의 반환 타입을 List<String> 으로 변경
- 클래스 이름 변경 -> GoogleBucketCloudService
- CloudBucketService 인터페이스를 사용하여 강한 종속성을 제거
- 판매자 문의 답변 완료처리 로직은 createSellerInquiryReply 메소드 안에서 호출하게 변경
- 예외를 메소드로 분리시켜 코드를 가독성 있게 개선
- 제곧내# Jwt 개선
- getRoles 메서드의 반환 타입을 List<String> 으로 변경
- 클래스 이름 변경 -> GoogleBucketCloudService
- CloudBucketService 인터페이스를 사용하여 강한 종속성을 제거
- 판매자 문의 답변 완료처리 로직은 createSellerInquiryReply 메소드 안에서 호출하게 변경
- 예외를 메소드로 분리시켜 코드를 가독성 있게 개선
- databases.properties 에서 redis.database = 1 설정 추가

전체적인 리팩토링 작업 및 Redis 설정

---

frontend/src/components/common/ScrollToTopButton.tsx
frontend/src/icons/Icons.tsx
frontend/src/layout/Header/Realtimekeyword.tsx
frontend/src/layout/Header/RealtimekeywordModal.tsx
frontend/src/pages/moreInformation/MoreInformation.tsx
frontend/src/pages/userService/Cart.tsx

fix: 아이콘 크기 수정

---

frontend/src/components/home/HomeItemList.tsx
frontend/src/components/product/Item.module.css
frontend/src/components/product/Item.tsx
frontend/src/components/product/SearchItemList.tsx
frontend/src/layout/Header/Realtimekeyword.tsx
frontend/src/layout/Header/RealtimekeywordModal.tsx
frontend/src/layout/Header/SearchInput.tsx
frontend/src/layout/mobile/MobileSearchModal.tsx
frontend/src/pages/auth/find/IdFind.tsx
frontend/src/pages/moreInformation/MoreInformation.tsx
frontend/src/pages/moreInformation/ProductInquiry.tsx
frontend/src/pages/moreInformation/review.tsx
frontend/src/pages/myPage/mySubPage/OrderManagement.tsx
frontend/src/pages/myPage/mySubPage/UserInfo.tsx
frontend/src/pages/userService/Payment.module.css
frontend/src/utils/adminsMaster/ImageUpload.tsx
frontend/src/utils/auth/AuthAPI.ts
frontend/src/utils/auth/token.ts
frontend/src/utils/product/cart.ts
frontend/src/utils/product/fetchProductList.ts
frontend/src/utils/product/payment.ts

- REACT_APP_API_URL 환경 변수를 이용해 개발과 배포 환경에서 다른 API baseURL 적용
- 기본값으로 로컬 개발 환경('http://localhost:8080')을 설정
- 배포 시 환경 변수 설정으로 자동으로 baseURL 변경 가능

chore: 개발, 배포 baseUrl분리

---

.github/workflows/cicd.yml

fix: ci/cd 에러 수정

---

frontend/netlify.toml
frontend/src/pages/myPage/mySubPage/AddressManagement.tsx
frontend/src/pages/myPage/mySubPage/InquiryHistory.tsx
frontend/src/pages/myPage/mySubPage/UserInfo.tsx
frontend/src/utils/error/axiosInstance.ts

- [refactor: base url 에러 수정](https://github.com/Kyungmin-University-Team-Project/everypet/commit/00e1b660b3ad3a48ee90f54cd2b648701262fb0a)

Develop0.1.9 [everypet]

---

src/main/java/com/everypet/review/controller/ReviewController.java

/product-review/insert form-data 형식으로 변경

feat : /product-review/insert 수정

---

src/main/java/com/everypet/member/controller/AddressApiController.java
src/main/java/com/everypet/member/service/impl/AddressServiceImpl.java

-주소 삭제 기능 개선: 정확한 예외 처리 및 안정성 향상.
-기본 주소 설정 로직 수정: 새 기본 주소지 추가 시, 기존 기본 주소는 자동으로 비활성화(N) 처리.

fix: 주소 관리 기능 개선
